excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- SwiftTemplate/AppDelegate.swift

# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 110

# or they can set both explicitly
file_length:
    warning: 500
    error: 1200
